# Generated by Django 4.2.16 on 2024-12-10 10:51

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='напишите название', max_length=150, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='напишите название', max_length=150, unique=True, verbose_name='название')),
                ('color', models.CharField(max_length=7, validators=[catalog.validators.HexColorValidator])),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], help_text='выберите размер', max_length=3, verbose_name='размер')),
                ('count', models.PositiveIntegerField(default=0, help_text='укажите количество', verbose_name='количество')),
                ('category', models.ForeignKey(help_text='выберите категорию', on_delete=django.db.models.deletion.CASCADE, related_name='tshirts', related_query_name='tshirts', to='catalog.category', verbose_name='категория')),
                ('color', models.ForeignKey(help_text='выберите цвет', on_delete=django.db.models.deletion.CASCADE, related_name='tshirts', related_query_name='tshirts', to='catalog.color', verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'футболка',
                'verbose_name_plural': 'футболки',
                'unique_together': {('category', 'color', 'size')},
            },
        ),
    ]
