# Generated by Django 4.2.16 on 2024-12-14 06:44

import core.models
import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructorProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IM", "На модерации"),
                            ("AC", "Принято"),
                            ("RJ", "Отказано"),
                        ],
                        default="IM",
                        help_text="выберите статус",
                        max_length=2,
                        verbose_name="статус модерации",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterField(
            model_name="color",
            name="color",
            field=models.CharField(
                help_text="напишите hex цвета иммет формат #008000",
                max_length=7,
                validators=[catalog.validators.HexColorValidator],
                verbose_name="hex цвета",
            ),
        ),
        migrations.CreateModel(
            name="ConstructorProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="загрузите изображение",
                        upload_to=core.models.get_path_image,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="товар изображения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        related_query_name="image",
                        to="catalog.constructorproduct",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.AddField(
            model_name="constructorproduct",
            name="item",
            field=models.ForeignKey(
                help_text="одежда товара",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="construct_products",
                related_query_name="construct_products",
                to="catalog.item",
                verbose_name="одежда",
            ),
        ),
    ]
