# Generated by Django 4.2.16 on 2024-12-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0003_alter_constructorproduct_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructorproduct",
            name="user",
            field=models.ForeignKey(
                default=1,
                help_text="пользователь, отправивший запрос",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="construct_products",
                related_query_name="construct_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
            preserve_default=False,
        ),
    ]
