# Generated by Django 4.2.16 on 2024-12-14 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_constructorproduct_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="укажите количество",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="количество",
            ),
        ),
    ]
