# Generated by Django 4.2.16 on 2024-12-15 14:35

import core.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_color_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructorEmbroideryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="загрузите изображение",
                        upload_to=core.models.get_path_image,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="товар изображения",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embroidery_image",
                        related_query_name="embroidery_image",
                        to="catalog.constructorproduct",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение вышивки",
                "verbose_name_plural": "изображения вышивки",
            },
        ),
    ]
