# Generated by Django 4.2.16 on 2024-12-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_constructorembroideryimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Garment",
        ),
        migrations.AlterModelOptions(
            name="garment",
            options={
                "verbose_name": "одежда",
                "verbose_name_plural": "одежды",
            },
        ),
        migrations.RenameField(
            model_name="constructorproduct",
            old_name="item",
            new_name="garment",
        ),
    ]
