# Generated by Django 4.2.16 on 2024-12-24 03:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0010_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="атегория товара",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="products",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="количество предмета корзины",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="количество",
                    ),
                ),
                (
                    "garment",
                    models.ForeignKey(
                        help_text="одежда предмета корзины",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.garment",
                        verbose_name="одежда",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="товар предмета корзины",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "предмет корзины",
                "verbose_name_plural": "предметы корзины",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        help_text="предметы корзины",
                        to="catalog.cartitem",
                        verbose_name="предметы корзины",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="пользователь корзины",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        related_query_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "корзина",
                "verbose_name_plural": "корзины",
            },
        ),
    ]
