# Generated by Django 4.2.16 on 2024-12-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_category_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="garment",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="цена одежды", verbose_name="цена"
            ),
        ),
    ]
