# Generated by Django 4.2.16 on 2024-12-25 19:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0013_alter_cartitem_options_remove_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "предмет корзины",
                "verbose_name_plural": "предметы корзины",
            },
        ),
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.CreateModel(
            name="CartItemQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="количество предмета в корзине",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="количество",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.cart",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.cartitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "количество предмета в корзине",
                "verbose_name_plural": "количества предметов в корзине",
            },
        ),
    ]
