# Generated by Django 4.2.16 on 2024-12-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_cartitem_options_remove_cart_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(
                help_text="предметы корзины",
                through="catalog.CartItemQuantity",
                to="catalog.cartitem",
                verbose_name="предметы корзины",
            ),
        ),
        migrations.AlterField(
            model_name="cartitemquantity",
            name="cart",
            field=models.ForeignKey(
                help_text="корзина",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.cart",
                verbose_name="корзина",
            ),
        ),
        migrations.AlterField(
            model_name="cartitemquantity",
            name="item",
            field=models.ForeignKey(
                help_text="предмет корзины",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.cartitem",
                verbose_name="предмет корзины",
            ),
        ),
    ]
