# Generated by Django 4.2.16 on 2024-12-26 08:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_cart_items_alter_cartitemquantity_cart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productadditionalimage",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="категория дополнительного изображения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_images",
                related_query_name="additional_images",
                to="catalog.category",
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productadditionalimage",
            name="color",
            field=models.ForeignKey(
                default=2,
                help_text="цвет дополнительного изображения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_images",
                related_query_name="additional_images",
                to="catalog.color",
                verbose_name="цвет",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="количество предмета корзины",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="коли��ество",
            ),
        ),
        migrations.AlterField(
            model_name="cartitemquantity",
            name="cart",
            field=models.ForeignKey(
                help_text="корзина",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartitemquantity_set",
                related_query_name="cartitemquantity_set",
                to="catalog.cart",
                verbose_name="корзина",
            ),
        ),
        migrations.AlterField(
            model_name="productadditionalimage",
            name="product",
            field=models.ForeignKey(
                help_text="товар дополнительного изображения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_images",
                related_query_name="additional_images",
                to="catalog.product",
                verbose_name="товар",
            ),
        ),
    ]
