# Generated by Django 4.2.16 on 2024-12-26 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_productadditionalimage_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="количество предмета корзины",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="количество",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="garments",
            field=models.ManyToManyField(
                help_text="одежда товара",
                related_name="products",
                related_query_name="products",
                to="catalog.garment",
                verbose_name="одежда",
            ),
        ),
    ]
