# Generated by Django 4.2.16 on 2024-12-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_cartitem_quantity_alter_product_garments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="garments",
            field=models.ManyToManyField(
                help_text="одежда товара",
                related_name="products",
                related_query_name="products",
                to="catalog.garment",
                verbose_name="одежды",
            ),
        ),
    ]
