# Generated by Django 4.2.16 on 2024-12-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_alter_product_garments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="quantity",
        ),
    ]
