# Generated by Django 4.2.16 on 2024-12-26 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0019_remove_cartitem_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WP", "Ожидание оплаты"),
                            ("IP", "В производстве"),
                            ("ID", "В доставке"),
                            ("DV", "Доставлен"),
                        ],
                        default="WP",
                        help_text="статус заказа",
                        max_length=2,
                        verbose_name="статус заказа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="дата создания заказа",
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="дата обновления заказа",
                        verbose_name="дата обновления",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="пользователь заказа",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        related_query_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="количество предмета в заказе",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="количество",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="цена на момент заказа", verbose_name="цена"
                    ),
                ),
                (
                    "garment",
                    models.ForeignKey(
                        help_text="одежда предмета заказа",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.garment",
                        verbose_name="одежда",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="заказ предмета",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        related_query_name="items",
                        to="catalog.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="товар предмета заказа",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "предмет заказа",
                "verbose_name_plural": "предметы заказа",
            },
        ),
    ]
