# Generated by Django 4.2.16 on 2024-12-26 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                default=1,
                help_text="корзина",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="items",
                to="catalog.cart",
                verbose_name="корзина",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="количество предмета в корзине",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="количество",
            ),
        ),
        migrations.DeleteModel(
            name="CartItemQuantity",
        ),
    ]
