# Generated by Django 4.2.16 on 2024-12-29 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_sum",
            field=models.PositiveIntegerField(
                default=0,
                help_text="сумма заказа",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="сумма заказа",
            ),
        ),
    ]
