# Generated by Django 4.2.16 on 2024-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("WP", "Ожидает оплаты"),
                    ("PD", "В разработке"),
                    ("IW", "На шитье"),
                    ("ID", "В доставке"),
                    ("DV", "Доставлен"),
                    ("CN", "Отменён"),
                ],
                default="WP",
                help_text="статус заказа",
                max_length=2,
                verbose_name="статус заказа",
            ),
        ),
    ]
