# Generated by Django 4.2.16 on 2024-12-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_order_confirmation_url_order_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="unique_user_waiting_payment",
        ),
    ]
