# Generated by Django 4.2.16 on 2025-01-01 09:52

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_alter_product_embroidery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                help_text="номер телефона пользователя",
                max_length=18,
                validators=[catalog.validators.validate_russian_phone],
                verbose_name="номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("WP", "Ожидает оплаты"),
                    ("PD", "В разработке"),
                    ("IW", "На шитье"),
                    ("DR", "Собирается"),
                    ("ID", "В доставке"),
                    ("DV", "Доставлен"),
                    ("CN", "Отменён"),
                ],
                default="WP",
                help_text="статус заказа",
                max_length=2,
                verbose_name="статус заказа",
            ),
        ),
    ]
