# Generated by Django 4.2.16 on 2025-01-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_alter_order_phone_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                help_text="код отслеживания товара",
                max_length=255,
                null=True,
                verbose_name="код отслеживания",
            ),
        ),
    ]
