# Generated by Django 4.2.16 on 2025-01-01 13:54

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0035_order_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="embroidery",
            field=models.FileField(
                blank=True,
                help_text="файл вышивки товара",
                null=True,
                upload_to=catalog.models.get_path_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jef", "emb", "dst"]
                    )
                ],
                verbose_name="файл вышивки",
            ),
        ),
    ]
