# Generated by Django 4.2.16 on 2025-01-02 13:10

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_alter_product_embroidery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="embroidery",
        ),
        migrations.CreateModel(
            name="ProductEmbroideryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embroidery",
                    models.FileField(
                        help_text="файл вышивки товара",
                        upload_to=catalog.models.get_path_file,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jef", "emb", "dst"]
                            )
                        ],
                        verbose_name="файл вышивки",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="товар файла вышивки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embroidery_file",
                        related_query_name="embroidery_file",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
        ),
    ]
