# Generated by Django 4.2.16 on 2025-01-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0037_remove_product_embroidery_productembroideryfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="productembroideryfile",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="категория файла вышивки",
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
    ]
