# Generated by Django 4.2.16 on 2025-01-11 13:39

import catalog.models
import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0039_alter_productembroideryfile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="категория товара",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="products",
                to="catalog.category",
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="embroidery",
            field=models.FileField(
                default=1,
                help_text="файл вышивки товара",
                upload_to=catalog.models.get_path_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jef", "emb", "dst"]
                    ),
                    catalog.validators.validate_file_size,
                ],
                verbose_name="файл вышивки",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProductEmbroideryFile",
        ),
    ]
