# Generated by Django 4.2.16 on 2025-01-17 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0042_alter_garment_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="цена товара",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="цена",
            ),
        ),
    ]
