# Generated by Django 4.2.16 on 2025-01-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0043_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productadditionalimage",
            name="category",
        ),
    ]
