# Generated by Django 4.2.16 on 2025-01-17 06:31

import core.models
import django.core.validators
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0044_remove_productadditionalimage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructorembroideryimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="загрузите изображение",
                upload_to=core.models.get_path_image,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="constructorproductimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="загрузите изображение",
                upload_to=core.models.get_path_image,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="productadditionalimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="загрузите изображение",
                upload_to=core.models.get_path_image,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="загрузите изображение",
                upload_to=core.models.get_path_image,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="изображение",
            ),
        ),
    ]
