# Generated by Django 4.2.16 on 2025-01-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0045_alter_constructorembroideryimage_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-id",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
