# Generated by Django 4.2.16 on 2025-01-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0047_alter_product_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="garments",
        ),
    ]
