# Generated by Django 4.2.16 on 2025-01-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0049_product_garments"),
    ]

    operations = [
        migrations.AddField(
            model_name="productadditionalimage",
            name="category",
            field=models.ForeignKey(
                default=1,
                help_text="категория дополнительного изображения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_images",
                related_query_name="additional_images",
                to="catalog.category",
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
    ]
