# Generated by Django 4.2.16 on 2025-01-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0050_productadditionalimage_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
