# Generated by Django 4.2.16 on 2025-01-18 12:43

import catalog.models
import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0051_remove_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="embroidery",
            field=models.FileField(
                default=1,
                help_text="файл вышивки товара",
                upload_to=catalog.models.get_path_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jef", "emb", "dst"]
                    ),
                    catalog.validators.validate_file_size,
                ],
                verbose_name="файл вышивки",
            ),
            preserve_default=False,
        ),
    ]
