# Generated by Django 4.2.16 on 2025-01-28 17:16

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0052_alter_product_embroidery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="загрузите изображение",
                        upload_to=core.models.get_path_image,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="изображение",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="товар главное изображение",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        related_query_name="main_image",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение товара",
                "verbose_name_plural": "изображения товаров",
            },
        ),
        migrations.CreateModel(
            name="ProductSecondaryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="загрузите изображение",
                        upload_to=core.models.get_path_image,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="изображение",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="товар дополнительное изображение",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_images",
                        related_query_name="secondary_images",
                        to="catalog.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "дополнительное изображение товара",
                "verbose_name_plural": "дополнительные изображения товаров",
            },
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
