# Generated by Django 4.2.16 on 2025-01-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0053_productmainimage_productsecondaryimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsecondaryimage",
            name="product",
            field=models.OneToOneField(
                help_text="товар дополнительное изображение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_images",
                related_query_name="secondary_images",
                to="catalog.product",
                verbose_name="товар",
            ),
        ),
    ]
