# Generated by Django 4.2.16 on 2025-01-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="дата обновления"
            ),
        ),
    ]
