# Generated by Django 4.2.16 on 2025-01-12 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0002_chat_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="responsible_users",
            field=models.ManyToManyField(
                related_name="responsible_chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ответственные пользователи",
            ),
        ),
    ]
