# Generated by Django 4.2.16 on 2025-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_chat_responsible_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_system",
            field=models.BooleanField(
                default=False, verbose_name="системное сообщение"
            ),
        ),
    ]
