# Generated by Django 4.2.16 on 2025-01-02 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0036_alter_product_embroidery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("WP", "Ожидает оплаты"),
                            ("PD", "В разработке"),
                            ("IW", "На шитье"),
                            ("DR", "Собирается"),
                            ("ID", "В доставке"),
                            ("DV", "Доставлен"),
                            ("CN", "Отменён"),
                        ],
                        max_length=2,
                        verbose_name="предыдущий статус",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("WP", "Ожидает оплаты"),
                            ("PD", "В разработке"),
                            ("IW", "На шитье"),
                            ("DR", "Собирается"),
                            ("ID", "В доставке"),
                            ("DV", "Доставлен"),
                            ("CN", "Отменён"),
                        ],
                        max_length=2,
                        verbose_name="новый статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "error_comment",
                    models.TextField(
                        blank=True,
                        help_text="заполняется только при возврате на предыдущий статус",
                        null=True,
                        verbose_name="комментарий об ошибке",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="catalog.order",
                        verbose_name="заказ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог заказа",
                "verbose_name_plural": "логи заказов",
                "ordering": ["-created_at"],
            },
        ),
    ]
