# Generated by Django 4.2.16 on 2025-01-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderLog",
        ),
    ]
