http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.monitoring.enabled: true
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 3s