# Generated by Django 4.2.16 on 2024-12-17 06:53

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Пользователь с таким email уже существует."
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "Пользователь с таким именем уже существует."
                },
                help_text="username_field_help",
                max_length=32,
                unique=True,
                validators=[users.validators.UsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
