# Generated by Django 4.2.16 on 2025-01-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="ID в Telegram",
                max_length=100,
                null=True,
                verbose_name="ID в Telegram",
            ),
        ),
    ]
