# Generated by Django 4.2.16 on 2025-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("moderator", "Модератор"),
                    ("designer", "Дизайнер"),
                    ("embroiderer", "Вышивальщик"),
                    ("courier", "Курьер"),
                    ("developer", "Разработчик"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
